---
project_name: uni

before:
  hooks:
    - go mod download

builds:
  - binary: uni
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    ignore:
      - goos: linux
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .RawVersion }}{{ if .Prerelease }}-{{ .Prerelease }}{{ end }}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.xz
    wrap_in_directory: "true"
    files:
      - none*

snapshot:
  name_template: "{{ .Tag }}-devel"

checksum:
  disable: true

changelog:
  skip: true
