name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-custom
      - v[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*-custom
      - v[0-9]+.[0-9]+.[0-9]+-*-custom-r[0-9]+

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
