name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-custom
      - v[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*-custom
      - v[0-9]+.[0-9]+.[0-9]+-*-custom-r[0-9]+

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
